name: Configure Code

on:
  workflow_dispatch:
    inputs:
      job-id:
        description: "Job ID"
        required: true
      project-id:
        description: "Project ID"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  configure:
    name: Configure Code
    runs-on: ubuntu-latest

    env:
      JOB_ID: ${{ inputs['job-id'] }}
      PROJECT_ID: ${{ inputs['project-id'] }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_OIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Create Sample Source Code
        run: |
          mkdir -p sample-project/{src,config,docs}

          echo "# Sample Project" > sample-project/README.md
          echo "This is a sample project generated by the no-code app builder."

          echo "console.log('Hello from sample app!');" > sample-project/src/index.js
          echo "module.exports = { version: '1.0.0' };" > sample-project/package.json

          echo "Sample configuration file" > sample-project/config/app.json
          echo "Sample documentation" > sample-project/docs/README.md

          zip -r source.zip sample-project/

          echo "Created source.zip with sample project structure"

      - name: Upload to S3
        run: |
          aws s3 cp source.zip s3://${{ secrets.AWS_BUCKET }}/projects/${{ env.PROJECT_ID }}/artifacts/source.zip

      - name: Report Job Status
        run: |
          response=$(curl -s -X PATCH "https://75d015e8ee64.ngrok-free.app/api/projects/${{ env.PROJECT_ID }}/downloads/${{ env.JOB_ID }}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" \
            -d "status=completed")

          echo "Response: $response"
